id: A12855B73
base_file: fA47A.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:14:57.945677
  last_modified_at: 2022-06-15 20:14:57.945682
