id: A12855B73
base_file: f4872.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:14:57.942177
  last_modified_at: 2022-06-15 20:14:57.942185
